image: gitpod/workspace-full-vnc

tasks:
  - name: build the qgis container
    init: docker build -t desktop-qgis .
    command: docker run --rm -ti --env=DISPLAY=unix${DISPLAY} --volume=/tmp/.X11-unix:/tmp/.X11-unix --volume=${HOME}:${HOME} desktop-qgis

  # this is in a task instead of in the "ports" section to force https
  - name: open the VNC server window in the browser
    command: gp preview https://localhost:6080
